Разметка внутренней страницы(2)
htmlacademy-htmlcss/1487393-technomart-29 pull request #3
Opened 2020-09-17 11:10 UTC by AlexGrink

2020-09-17 13:00 UTC, mkolotovich requested changes
В пагинации в список перенеси кнопку Следующая и измени ее на ссылку.

2020-09-17 13:44 UTC, mkolotovich requested changes
Сделай базовую стилизацию

2020-09-20 12:35 UTC, mkolotovich requested changes

2020-09-20 12:35 UTC, mkolotovich commented on css/style.css
> +  color: var(--basic-white)
Измени на #F1F5F7

2020-09-20 12:35 UTC, mkolotovich commented on css/style.css
> +}
Селектору .footer-contacts задай color: #F3F7F9;

2020-09-20 12:35 UTC, mkolotovich commented on css/style.css
> +}
Создай селектор .footer-nav-bottom li:nth-child(2) a и задай ему color: #FFDA96;

2020-09-20 12:35 UTC, mkolotovich commented on css/style.css
> +  background-color: var(--basic-dark);
Измени на background: #32425C;

2020-09-20 12:35 UTC, mkolotovich commented on css/style.css
> +
Создай селектор .promo-item:last-child  и задай ему background: #FFC047;

2020-09-20 12:35 UTC, mkolotovich commented on css/style.css
> +  background-color: var(--beige);
Измени на #F9F5F0;

2020-09-20 17:00 UTC, AlexGrink commented on css/style.css
> +}
Как такое извращение можно на макете заметить?)

2020-09-20 17:15 UTC, AlexGrink commented on css/style.css
> +  background-color: var(--beige);
+

2020-09-20 17:15 UTC, AlexGrink commented on css/style.css
> +
+

2020-09-20 17:15 UTC, AlexGrink commented on css/style.css
> +  background-color: var(--basic-dark);
+

2020-09-21 09:17 UTC, mkolotovich commented on css/style.css
> +}
Я уже просто 4 интенсив провожу с этими макетами, а косяк в макете так и не исправляют из потока в поток). Ну вообще стайлгайд приоритетнее, так что если на стайлгайде #FFD180, оставляй как в стайлгайде.

2020-09-21 10:56 UTC, mkolotovich requested changes
Добавь шрифт PT Sans как ты добавлял Cuprum, чтобы он у тебя заработал на странице

2020-09-21 10:56 UTC, mkolotovich commented on css/style.css
>  .promo-item a {
Создай селектор .promo-item a:hover и задай ему background: rgba(197,197,197,0.3);

2020-09-21 10:56 UTC, mkolotovich commented on css/style.css
>  .promo-item a {
Создай селектор .promo-item a:active и задай ему background: rgba(169,169,169,0.3);

2020-09-21 10:56 UTC, mkolotovich commented on css/style.css
Создай селектор .button:hover и задай ему background: #CA2C37;

2020-09-21 10:56 UTC, mkolotovich commented on css/style.css
Создай селектор .button:active и задай ему background: #BA2732;

2020-09-21 10:56 UTC, mkolotovich commented on css/style.css
>  .services-list-item:not(.services-list-delivery) a {
Создай селектор .services-list-item:not(.services-list-delivery) a:hover и задай ему background: #293449

2020-09-21 10:56 UTC, mkolotovich commented on css/style.css
Создай селектор .footer-nav .site-navigation-item a:hover и задай ему text-decoration-line: underline;

2020-09-21 10:56 UTC, mkolotovich commented on css/style.css
Создай селектор .footer-nav .site-navigation-item a:active и задай ему opacity: 0.5;

2020-09-21 10:56 UTC, mkolotovich commented on css/style.css
> +
Создай селектор .footer-text a:hover и задай ему text-decoration-line: underline;

2020-09-21 10:56 UTC, mkolotovich commented on css/style.css
> +
Создай селектор .footer-text a:active и задай ему color: #EE3643;

2020-09-22 08:49 UTC, mkolotovich commented on index.html
>    <link href="normalize.css" rel="stylesheet">
Ты подключаешь к странице normalize, а сам файл normalize.css отсутствует. Либо добавь файл с normalize.css в проект либо удали его подключение на странице. Тоже самое проделай и на внутренней странице

2020-09-22 08:49 UTC, mkolotovich commented on css/style.css
Не исправлено, добавь еще селектору .footer-nav .site-navigation-item a:hover background: transparent;

2020-09-22 08:51 UTC, mkolotovich commented on css/style.css
Не исправлено

2020-09-22 08:54 UTC, mkolotovich requested changes
Исправь 2 не исправленных замечания с прошлой проверки и одно с этой и мердж

2020-09-22 12:48 UTC, mkolotovich reviewed
Исправь 1 не исправленное замечание с прошлой проверки

2020-09-22 12:58 UTC, merged